CREATE TABLE Posts (
    PostId TEXT NOT NULL PRIMARY KEY,
    State INTEGER NOT NULL,
    StateOverride INTEGER NULL);

CREATE TABLE Comments (
    PostId TEXT NOT NULL,
    CommentId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Visible BOOLEAN NOT NULL,
    Author TEXT NOT NULL,
    Date DATETIME NOT NULL,
    Text TEXT NOT NULL,
    FOREIGN KEY (PostId) REFERENCES Posts(PostId));
